version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: slotsync_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: slotsync
    ports:
      - "5432:5432"
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d slotsync"]
      interval: 5s
      timeout: 5s
      retries: 5