from pydantic import BaseModel, UUID4, Field
from datetime import datetime

class BookingRequest(BaseModel):
    # The slot the user is trying to book
    slot_id: UUID4
    # The unique key generated by the frontend to prevent double-charging/booking
    idempotency_key: str = Field(..., min_length=10, max_length=255)
    
class BookingResponse(BaseModel):
    slot_id: UUID4
    status: str
    message: str
    timestamp: datetime

class SlotCreate(BaseModel):
    start_time: datetime
    end_time: datetime