from pydantic import BaseModel, UUID4, Field, ConfigDict
from datetime import datetime, date, time

class BookingRequest(BaseModel):
    # The slot the user is trying to book
    slot_id: UUID4
    # The unique key generated by the frontend to prevent double-charging/booking
    idempotency_key: str = Field(..., min_length=10, max_length=255)
    
class BookingResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    slot_id: UUID4
    status: str
    message: str
    timestamp: datetime

class SlotCreate(BaseModel):
    start_time: datetime
    end_time: datetime


class SlotResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID4
    owner_id: str | None = None
    start_time: datetime
    end_time: datetime
    status: str
    version: int
    provider_id: UUID4 | None = None
    appointment_type_id: UUID4 | None = None


class AppointmentTypeCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=255)
    description: str = Field(..., min_length=1)
    duration_minutes: int = Field(..., gt=0)
    active: bool = True


class AppointmentTypeResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID4
    name: str
    description: str
    duration_minutes: int
    active: bool
    created_at: datetime


class ProviderCreate(BaseModel):
    user_id: str = Field(..., min_length=1, max_length=255)
    name: str = Field(..., min_length=1, max_length=255)
    description: str = Field(..., min_length=1)
    active: bool = True


class ProviderResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID4
    user_id: str
    name: str
    description: str
    active: bool
    created_at: datetime


class AssignAppointmentTypeRequest(BaseModel):
    appointment_type_id: UUID4


class SlotGenerateRequest(BaseModel):
    date: date
    start_time: time
    end_time: time
    duration_minutes: int = Field(..., gt=0)
    provider_id: UUID4